services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8123:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3123:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8123}
    depends_on:
      - api
    restart: unless-stopped

volumes:
  web_node_modules:
